// Generates THIRD_PARTY_NOTICES.md: every JavaScript package and Rust crate
// that goes into Taskhop, with its license text. Run before each release:
//   pnpm notices
import { execSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const OUT = 'THIRD_PARTY_NOTICES.md'
const LICENSE_FILE = /^(licen[cs]e|copying|notice|unlicense)([-._].*)?$/i

/** License and notice files shipped in a package folder. */
function licenseTexts(dir) {
  if (!dir || !existsSync(dir)) return []
  return readdirSync(dir)
    .filter((file) => LICENSE_FILE.test(file))
    .sort()
    .map((file) => readFileSync(join(dir, file), 'utf8').replace(/\r\n/g, '\n').trim())
    .filter(Boolean)
}

const run = (cmd) => execSync(cmd, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 })

// JavaScript: production dependencies (what ends up in the app's bundle).
const components = []
const js = JSON.parse(run('pnpm licenses list --prod --json'))
for (const packages of Object.values(js)) {
  for (const p of packages) {
    components.push({
      kind: 'npm',
      name: p.name,
      version: p.versions.join(', '),
      license: p.license,
      texts: licenseTexts(p.paths[0]),
    })
  }
}

// Rust: crates used when building for Windows or macOS, except Taskhop itself.
const TARGETS = ['x86_64-pc-windows-msvc', 'aarch64-apple-darwin', 'x86_64-apple-darwin']
const used = new Set()
let meta
for (const target of TARGETS) {
  meta = JSON.parse(
    run(`cargo metadata --format-version 1 --manifest-path src-tauri/Cargo.toml --filter-platform ${target}`),
  )
  for (const node of meta.resolve.nodes) used.add(node.id)
}
for (const p of meta.packages) {
  if (!used.has(p.id) || meta.workspace_members.includes(p.id)) continue
  components.push({
    kind: 'crate',
    name: p.name,
    version: p.version,
    license: p.license ?? 'see license file',
    texts: licenseTexts(dirname(p.manifest_path)),
  })
}

// Merge versions of the same package and sort by name.
const byName = new Map()
for (const c of components) {
  const key = `${c.kind}:${c.name}`
  const seen = byName.get(key)
  if (seen) {
    if (!seen.version.split(', ').includes(c.version)) seen.version += `, ${c.version}`
    if (!seen.texts.length) seen.texts = c.texts
  } else byName.set(key, { ...c })
}
const all = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name))

// Group identical license texts so each is printed once.
const textGroups = new Map()
const missing = []
for (const c of all) {
  if (!c.texts.length) {
    missing.push(c)
    continue
  }
  const text = c.texts.join('\n\n---\n\n')
  if (!textGroups.has(text)) textGroups.set(text, [])
  textGroups.get(text).push(`${c.name} ${c.version}`)
}

const lines = [
  '# Third-party notices',
  '',
  'Taskhop is made by MoebiusD9 and released under the MIT License (see `LICENSE`).',
  'It includes the open-source software listed below. Each component is used',
  'under its own license; the full license texts follow.',
  '',
  'This file is generated by `pnpm notices` (scripts/notices.mjs).',
  '',
  '## Other credits',
  '',
  '- **Lucide icons** (https://lucide.dev) — the settings, pin, trash and arrow',
  '  icons are based on Lucide. ISC License, Copyright (c) for portions of Lucide are',
  '  held by Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c)',
  '  for Lucide are held by Lucide Contributors 2022.',
  '- **SQLite** (https://sqlite.org) — public domain, bundled through the',
  '  `libsqlite3-sys` crate.',
  '- **NSIS** (https://nsis.sourceforge.io) — the Windows installer is built with',
  '  NSIS, zlib/libpng License.',
  '',
  '## Components',
  '',
  '| Component | Version | Source | License |',
  '|---|---|---|---|',
  ...all.map((c) => `| ${c.name} | ${c.version} | ${c.kind} | ${c.license} |`),
  '',
  '## License texts',
  '',
]
for (const [text, names] of textGroups) {
  lines.push(`### ${names.length === 1 ? names[0] : `${names.length} components`}`, '')
  if (names.length > 1) lines.push(`Used by: ${names.join(', ')}`, '')
  lines.push('```text', text.replace(/```/g, "'''"), '```', '')
}
if (missing.length) {
  lines.push(
    '## Components without a bundled license file',
    '',
    'These packages do not ship a license file; they are used under the license',
    'named above, whose standard text is at https://spdx.org/licenses/.',
    '',
    ...missing.map((c) => `- ${c.name} ${c.version} (${c.license})`),
    '',
  )
}

writeFileSync(OUT, lines.join('\n'))
console.log(`${OUT}: ${all.length} components, ${textGroups.size} distinct license texts, ${missing.length} without a file`)
